import { useEffect, useMemo } from "react";
import { Link } from "react-router-dom";
import { ShieldCheck, ShieldAlert, Eye, ShieldX, Bell, CheckCheck, CircleCheck, Lock } from "lucide-react";
import { Card, Button, EmptyState, Skeleton, Badge } from "@/shared/components";
import { PageHeader } from "@/shared/layout/components/Content/PageHeader";
import { useNotifications, useMarkAllNotificationsRead } from "@/features/notifications/hooks";
import { formatRelativeTime } from "@/shared/lib/format";
import { cn } from "@/shared/utils";

const SEVERITY_META = {
  LOW: { label: "Informational", icon: Eye, tone: "bg-info-subtle text-info" },
  MEDIUM: { label: "Action recommended", icon: ShieldCheck, tone: "bg-warning-subtle text-pending" },
  HIGH: { label: "Urgent", icon: ShieldAlert, tone: "bg-danger-subtle text-debit" },
} as const;

function severityOf(title: string, message: string): keyof typeof SEVERITY_META {
  const text = `${title} ${message}`.toLowerCase();
  if (/(suspicious|unauthorized|breach|blocked|failed login)/.test(text)) return "HIGH";
  if (/(changed|updated|password|device|verification|enabled)/.test(text)) return "MEDIUM";
  return "LOW";
}

export function SecurityPage() {
  const { data, isLoading } = useNotifications({ notificationType: "SECURITY", page: 0, size: 50 });
  const markAll = useMarkAllNotificationsRead();

  const securityEvents = useMemo(() => data?.content ?? [], [data]);

  useEffect(() => {
    const unread = securityEvents.some((n) => !n.isRead);
    if (unread) markAll.mutate();
  }, [securityEvents, markAll]);

  if (isLoading) {
    return (
      <div className="space-y-6">
        <PageHeader title="Security Center" subtitle="Protect your account" />
        <Skeleton className="h-40 rounded-2xl" />
        <Skeleton className="h-64 rounded-2xl" />
      </div>
    );
  }

  const highAlerts = securityEvents.filter((n) => severityOf(n.title, n.message) === "HIGH").length;

  return (
    <div className="space-y-6">
      <PageHeader
        title="Security Center"
        subtitle="Real-time account protection, driven by your security events"
      />

      {/* Status hero */}
      <div className="relative overflow-hidden rounded-2xl border border-border-default bg-surface-primary p-6">
        <div className="pointer-events-none absolute inset-0" aria-hidden="true">
          <div
            className="absolute -right-20 -top-24 h-72 w-72 rounded-full opacity-25"
            style={{ background: "radial-gradient(closest-side, var(--ff-color-primary, #2fd6a3), transparent)" }}
          />
        </div>
        <div className="relative flex flex-wrap items-center gap-5">
          <span className="flex h-14 w-14 items-center justify-center rounded-2xl bg-success-subtle text-credit">
            <ShieldCheck size={28} />
          </span>
          <div className="flex-1">
            <h2 className="text-xl font-bold tracking-tight text-text-primary">Your account is protected</h2>
            <p className="mt-0.5 text-sm text-text-tertiary">
              {highAlerts === 0
                ? "No urgent security alerts. We monitor activity continuously."
                : `${highAlerts} urgent alert${highAlerts === 1 ? "" : "s"} — review them below.`}
            </p>
          </div>
          <div className="flex flex-wrap gap-5 text-sm">
            <div className="rounded-lg border border-border-subtle bg-bg-secondary px-4 py-2.5">
              <p className="flex items-center gap-1.5 text-xs text-text-tertiary"><Lock size={13} /> Status</p>
              <p className="mt-0.5 font-medium text-credit">Active &amp; healthy</p>
            </div>
            <div className="rounded-lg border border-border-subtle bg-bg-secondary px-4 py-2.5">
              <p className="flex items-center gap-1.5 text-xs text-text-tertiary"><Bell size={13} /> Events</p>
              <p className="mt-0.5 font-medium text-text-primary">{highAlerts} urgent</p>
            </div>
            <div className="rounded-lg border border-border-subtle bg-bg-secondary px-4 py-2.5">
              <p className="flex items-center gap-1.5 text-xs text-text-tertiary"><CheckCheck size={13} /> Verified</p>
              <p className="mt-0.5 font-medium text-text-primary">Identity confirmed</p>
            </div>
          </div>
        </div>
      </div>

      {/* Events timeline */}
      <Card>
        <div>
          <h3 className="text-base font-semibold tracking-tight text-text-primary">Security events</h3>
          <p className="text-sm text-text-tertiary">Alerts generated by your bank, in real time.</p>
        </div>

        {securityEvents.length === 0 ? (
          <EmptyState
            icon={<ShieldX className="h-10 w-10 text-text-disabled" />}
            title="No security events"
            description="You're all clear — we'll surface any security activity here the moment it happens."
          />
        ) : (
          <ul className="space-y-1">
            {securityEvents.map((event) => {
              const severity = severityOf(event.title, event.message);
              const meta = SEVERITY_META[severity];
              const Icon = meta.icon;
              return (
                <li key={event.id} className="flex items-start gap-3 rounded-lg px-2 py-3 transition-colors hover:bg-bg-secondary">
                  <span className={cn("flex h-9 w-9 shrink-0 items-center justify-center rounded-lg", meta.tone)}>
                    <Icon size={16} />
                  </span>
                  <div className="min-w-0 flex-1">
                    <div className="flex flex-wrap items-center gap-2">
                      <p className="text-sm font-medium text-text-primary">{event.title}</p>
                      <Badge variant="neutral" size="sm">{meta.label}</Badge>
                    </div>
                    <p className="mt-0.5 text-sm text-text-tertiary">{event.message}</p>
                  </div>
                  <div className="shrink-0 text-right">
                    <p className="text-xs text-text-tertiary">{formatRelativeTime(event.createdAt)}</p>
                    {event.isRead ? (
                      <span className="inline-flex items-center gap-1 text-xs text-credit">
                        <CircleCheck size={12} /> Reviewed
                      </span>
                    ) : (
                      <Badge variant="danger" size="sm">New</Badge>
                    )}
                  </div>
                </li>
              );
            })}
          </ul>
        )}
      </Card>

      {/* Hardening checklist */}
      <Card>
        <h3 className="text-base font-semibold tracking-tight text-text-primary">Strengthen your account</h3>
        <div className="mt-4 grid gap-3 sm:grid-cols-2">
          <Link
            to="/profile"
            className="flex items-center justify-between rounded-xl border border-border-subtle bg-bg-secondary px-4 py-3 transition-colors hover:border-border-strong"
          >
            <div>
              <p className="text-sm font-medium text-text-primary">Verify your identity</p>
              <p className="text-xs text-text-tertiary">Add verification to unlock full trust level</p>
            </div>
            <Button variant="ghost" size="sm">Review</Button>
          </Link>
          <Link
            to="/settings"
            className="flex items-center justify-between rounded-xl border border-border-subtle bg-bg-secondary px-4 py-3 transition-colors hover:border-border-strong"
          >
            <div>
              <p className="text-sm font-medium text-text-primary">Notification preferences</p>
              <p className="text-xs text-text-tertiary">Choose how you're alerted to account activity</p>
            </div>
            <Button variant="ghost" size="sm">Manage</Button>
          </Link>
        </div>
      </Card>
    </div>
  );
}