export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  VERIFY_OTP: "/verify-otp",
  DASHBOARD: "/dashboard",
  ACCOUNTS: "/accounts",
  TRANSFERS: "/transfers",
  TRANSACTIONS: "/transactions",
  BENEFICIARIES: "/beneficiaries",
  CARDS: "/cards",
  BUDGETS: "/budgets",
  SETTINGS: "/settings",
  PROFILE: "/profile",
  ADMIN: "/admin",
  NOTIFICATIONS: "/notifications",
  ANALYTICS: "/analytics",
  SECURITY: "/security",
} as const;

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    REFRESH: "/auth/refresh",
    REVOKE: "/auth/revoke",
    LOGOUT: "/auth/logout",
  },
  ACCOUNTS: {
    BASE: "/accounts",
    BY_ID: (id: string) => `/accounts/${id}` as const,
    STATUS: (id: string) => `/accounts/${id}/status` as const,
    CLOSE: (id: string) => `/accounts/${id}/close` as const,
    HISTORY: (id: string) => `/accounts/${id}/history` as const,
    HOLDS: (id: string) => `/accounts/${id}/holds` as const,
    RELEASE_HOLD: (id: string, holdId: string) =>
      `/accounts/${id}/holds/${holdId}/release` as const,
  },
  TRANSACTIONS: {
    BASE: "/transactions",
    DEPOSIT: "/transactions/deposit",
    WITHDRAWAL: "/transactions/withdrawal",
    TRANSFER: "/transactions/transfer",
    BY_ID: (id: string) => `/transactions/${id}` as const,
    CANCEL: (id: string) => `/transactions/${id}/cancel` as const,
  },
  BENEFICIARIES: {
    BASE: "/beneficiaries",
    BY_ID: (id: string) => `/beneficiaries/${id}` as const,
    STATUS: (id: string) => `/beneficiaries/${id}/status` as const,
  },
  TRANSFERS: {
    TEMPLATES: "/transfers/templates",
    TEMPLATE_BY_ID: (id: string) => `/transfers/templates/${id}` as const,
    SCHEDULED: "/transfers/scheduled",
    SCHEDULED_BY_ID: (id: string) => `/transfers/scheduled/${id}` as const,
    PAUSE: (id: string) => `/transfers/scheduled/${id}/pause` as const,
    RESUME: (id: string) => `/transfers/scheduled/${id}/resume` as const,
  },
  CARDS: {
    BASE: "/cards",
    BY_ID: (id: string) => `/cards/${id}` as const,
    FREEZE: (id: string) => `/cards/${id}/freeze` as const,
    UNFREEZE: (id: string) => `/cards/${id}/unfreeze` as const,
    BLOCK: (id: string) => `/cards/${id}/block` as const,
  },
  SAVINGS: {
    BASE: "/savings",
    BY_ID: (id: string) => `/savings/${id}` as const,
    DEPOSIT: (id: string) => `/savings/${id}/deposit` as const,
    PAUSE: (id: string) => `/savings/${id}/pause` as const,
    RESUME: (id: string) => `/savings/${id}/resume` as const,
  },
  ADMIN: {
    DASHBOARD: "/admin/dashboard",
    AUDIT_LOGS: "/admin/audit-logs",
    USERS: "/admin/users",
  },
  NOTIFICATIONS: {
    BASE: "/notifications",
    BY_ID: (id: string) => `/notifications/${id}` as const,
    UNREAD_COUNT: "/notifications/unread-count",
    MARK_ALL_READ: "/notifications/mark-all-read",
  },
  PROFILE: {
    BASE: "/profile",
  },
  SETTINGS: {
    BASE: "/settings",
    BY_KEY: (key: string) => `/settings/${key}` as const,
    BULK: "/settings/bulk",
  },
} as const;

export const QUERY_KEYS = {
  USER: ["user"] as const,
  ACCOUNTS: ["accounts"] as const,
  ACCOUNT_DETAIL: (id: string) => ["accounts", id] as const,
  ACCOUNT_HISTORY: (id: string) => ["accounts", id, "history"] as const,
  ACCOUNT_HOLDS: (id: string) => ["accounts", id, "holds"] as const,
  TRANSACTIONS: ["transactions"] as const,
  TRANSACTION_DETAIL: (id: string) => ["transactions", id] as const,
  BENEFICIARIES: ["beneficiaries"] as const,
  BENEFICIARY_DETAIL: (id: string) => ["beneficiaries", id] as const,
  TRANSFERS_TEMPLATES: ["transfers", "templates"] as const,
  TRANSFER_TEMPLATE_DETAIL: (id: string) => ["transfers", "templates", id] as const,
  TRANSFERS_SCHEDULED: ["transfers", "scheduled"] as const,
  SCHEDULED_TRANSFER_DETAIL: (id: string) => ["transfers", "scheduled", id] as const,
  CARDS: ["cards"] as const,
  CARD_DETAIL: (id: string) => ["cards", id] as const,
  SAVINGS: ["savings"] as const,
  SAVINGS_DETAIL: (id: string) => ["savings", id] as const,
  BUDGETS: ["budgets"] as const,
  PROFILE: ["profile"] as const,
  ADMIN_DASHBOARD: ["admin", "dashboard"] as const,
  ADMIN_AUDIT_LOGS: ["admin", "audit-logs"] as const,
  ADMIN_USERS: ["admin", "users"] as const,
  SETTINGS: ["settings"] as const,
  NOTIFICATIONS: ["notifications"] as const,
  NOTIFICATION_UNREAD_COUNT: ["notifications", "unread-count"] as const,
} as const;

export const STORAGE_KEYS = {
  THEME: "theme",
  SESSION: "session",
  REFRESH_TOKEN: "refresh_token",
} as const;